### ISSUE TITLE
<Cdrs> WARNING: Could not find CallCostLog for cgrid  (0.9.1~rc8)

### ISSUE THREAD

**Issue by acheraime** [cgrates/cgrates#385] opened 2016-03-01 14:06 UTC
Hi,

For every call a see a log entry as follow:
<Cdrs> WARNING: Could not find CallCostLog for cgrid: a0050185dbbcc52eac7a2d66b091a7acb61c3f3b, source: SMR, runid: *default, will recalculate

Can you guys tell me why cgrates keep complaining about CallCostLog?

Best

**Comment by danbogos** [comment] 2016-03-01 15:07
Hi  @acheraime,

This means that the session manager did not succeed saving the call cost 
in the storDb. I suspect a configuration issue there. If the call cost 
is recalculated you have chances for double charging. Maybe check if 
that is not the case.

DanB

PS: If possible, please direct your questions towards our google group 
since we plan keeping github for issues and feature requests. Thanks!

**Comment by MarcVoIP** [comment] 2016-03-02 23:46
Hi guys,
I'm having the same issue : latest cgrates master branch , latest go (1.6) and very simple config.

In my setup I have split the installation:  Session Manager and Freeswitch  on box 1,  Cgrates engine + Redis on box 2,   storDB on a separate box


In my system I see following issues:
 cgrates main server saves into the logs:
    "CGRateS[29969]: <Cdrs> WARNING: Could not find CallCostLog for cgrid: 565504795bc4e8e70a553be897a4b9688907b9b2, source: SMR, runid: *default, will recalculate"


 Session Manager gives me these error messages:
   1. after first call (after restart):
     CGRateS[30617]: <SM> ERROR failed to log call cost: unexpected EOF
       when doing tcpdump I see (480 Bad Request response from CGR main server (port 2080)
       this is applicable only for the first call after cgrates service reload

   2. for each and every call after that:
     CGRateS[1789]: <SM> ERROR failed to log call cost: connection is shut down
    

My CDRs are saved properly, I see the main server saves CDRs to StorDB after receiving POST on freeswitch_json

**Comment by MarcVoIP** [comment] 2016-04-01 14:16
Don't see this issue anymore on recent master branch version however the final CDR is not generated properly (not sure if this issue is related or not).

**Comment by danbogos** [comment] 2016-04-06 19:26
The reason it did not appear anymore it was a bug. I hope we have fixed it.

As per our investigation, the reason the log appeared to you was because you did not properly set cgr_reqtype in the freeswitch before sending the call to authorization, hence the call was never handled by FS in first place.

Please confirm so we can close the issue.

Thanks,
DanB

**Comment by MarcVoIP** [comment] 2016-04-07 08:13
Ok, confirmed. The message in the logs appears again.

**Comment by danbogos** [comment] 2016-04-07 12:50
Since I think there is no real issue with this log (except when the cost is really not found), will close the ticket, so @acheraime and @MarcVoIP please feel free to re-open if further issues.

DanB

**Closed by danbogos** 2016-04-07 12:50 UTC
