### ISSUE TITLE
Aliases seems not working with kamailio evapi

### ISSUE THREAD

**Issue by paolovisintin** [cgrates/cgrates#856] opened 2017-12-06 11:48 UTC
Hi everyone, I'm trying to implement Aliases module ; I'm working with kamailio+evapi ; 
in cgr-console everything seems working (`cgr-console 'aliases Direction="*out" Tenant="evox.it" Category="call" Account="0409811201" Subject="0409811201" Context="*rating"'`) but when kamailio makes authentication and asks fot "Responder.GetDerivedMaxSessionTime" Cgrates replies : "ACCOUNT_NOT_FOUND"; what could be wrong ?

`tp_aliases`
```
+----+------+-----------+---------+----------+------------+---------+----------------+---------+---------+----------+------------+--------+------------+
| id | tpid | direction | tenant  | category | account    | subject | destination_id | context | target  | original | alias      | weight | created_at |
+----+------+-----------+---------+----------+------------+---------+----------------+---------+---------+----------+------------+--------+------------+
|  1 | 2    | *out      | evox.it | call     | 0409811201 | *any    |                | *rating | Account | *any     | 0409828031 |  10.00 | NULL       |
|  2 | 2    | *out      | evox.it | call     | 0409811202 | *any    |                | *rating | Account | *any     | 0409828031 |  10.00 | NULL       |
+----+------+-----------+---------+----------+------------+---------+----------------+---------+---------+----------+------------+--------+------------+
```
on `RALs` ngrep -W byline port 2012
```
T 10.32.0.1:46076 -> 10.32.0.236:2012 [AP]
{"method":"Responder.GetDerivedMaxSessionTime","params":[{"CGRID":"83cef65a7598474fa6f0ed631b59750d952eac55","RunID":"","OrderID":0,"OriginHost":"127.0.0.1","Source":"KAMAILIO_CGR_AUTH_REQUEST","OriginID":";","ToR":"*voice","RequestType":"*prepaid","Direction":"*out","Tenant":"evox.it","Category":"call","Account":"0409811201","Subject":"0409811201","Destination":"0039040123532","SetupTime":"2017-12-06T11:30:36Z","PDD":0,"AnswerTime":"0001-01-01T00:00:00Z","Usage":0,"Supplier":"","DisconnectCause":"","ExtraFields":{"cgr_computelcr":"true","tr_index":"11028","tr_label":"537416753"},"CostSource":"","Cost":-1,"CostDetails":null,"AccountSummary":null,"ExtraInfo":"","Rated":false,"Partial":false}],"id":8}

##
T 10.32.0.236:2012 -> 10.32.0.1:46076 [AP]
{"id":8,"result":null,"error":"ACCOUNT_NOT_FOUND"}
```

`config.json` (abstract)
```

 "rals": {
     "enabled": true,                        // enable Rater service: <true|false>
     "aliases_conns": [
		{"address": "*internal"}
	]
},
...
 "aliases": {
	"enabled": true,
},
```

**Comment by paolovisintin** [comment] 2017-12-06 15:05
Attached also targz of all csv files
[tutorial.tar.gz](https://github.com/cgrates/cgrates/files/1535607/tutorial.tar.gz)

**Comment by danbogos** [comment] 2017-12-08 18:42
Hi @paolovisintin 

I have tried reproducing your issue using the files provided but without  much luck.
One thing which I have corrected was Subject -> Account in your Aliases.csv since Subject was duplicated.

After loading the files (redis/mysql config), I got this answer to the RPC you posted:
`{"method":"Responder.GetDerivedMaxSessionTime","params":[{"CGRID":"83cef65a7598474fa6f0ed631b59750d952eac55","RunID":"","OrderID":0,"OriginHost":"127.0.0.1","Source":"KAMAILIO_CGR_AUTH_REQUEST","OriginID":";","ToR":"*voice","RequestType":"*prepaid","Direction":"*out","Tenant":"evox.it","Category":"call","Account":"0409811201","Subject":"0409811201","Destination":"0039040123532","SetupTime":"2017-12-06T11:30:36Z","PDD":0,"AnswerTime":"0001-01-01T00:00:00Z","Usage":0,"Supplier":"","DisconnectCause":"","ExtraFields":{"cgr_computelcr":"true","tr_index":"11028","tr_label":"537416753"},"CostSource":"","Cost":-1,"CostDetails":null,"AccountSummary":null,"ExtraInfo":"","Rated":false,"Partial":false}],"id":8}
{"id":8,"result":null,"error":"RATING_PLAN_NOT_FOUND"}
`

Did u test with the files provided also? Was it with mysql or mongo?

Ta,
DanB

**Comment by paolovisintin** [comment] 2017-12-11 14:36
Hi @danbogos , 
I tested with CSV and cgr-loader in order to load to `datadir`. No more MySQL, actually it's used only for cdrs

**Comment by danbogos** [comment] 2017-12-11 14:38
hi @paolovisintin 

Are you getting same results as I did?

Thanks,
DanB

**Comment by paolovisintin** [comment] 2017-12-11 14:52
@danbogos , I'm really sorry, actually restarting every container everything seems working good, also flushcache is working!!!!!

Thanks
```
T 10.32.0.1:49978 -> 10.32.0.94:2012 [AP]
{"method":"Responder.GetDerivedMaxSessionTime","params":[{"CGRID":"7542e9921dc447c7d28b3a75c726ce8d2eda0f66","RunID":"","OrderID":0,"OriginHost":"127.0.0.1","Source":"KAMAILIO_CGR_AUTH_REQUEST","OriginID":";","ToR":"*voice","RequestType":"*prepaid","Direction":"*out","Tenant":"evox.it","Category":"call","Account":"0409811201","Subject":"0409811201","Destination":"0039040789546","SetupTime":"2017-12-11T14:47:52Z","PDD":0,"AnswerTime":"0001-01-01T00:00:00Z","Usage":0,"Supplier":"","DisconnectCause":"","ExtraFields":{"cgr_computelcr":"true","tr_index":"33098","tr_label":"498540240"},"CostSource":"","Cost":-1,"CostDetails":null,"AccountSummary":null,"ExtraInfo":"","Rated":false,"Partial":false}],"id":47}

#
T 10.32.0.94:2012 -> 10.32.0.1:49978 [AP]
{"id":47,"result":595000000000,"error":null}
```

**Comment by danbogos** [comment] 2017-12-11 15:01
Sure, I was wondering why it does not make sense ;).

Have a good one!

DanB

**Comment by paolovisintin** [comment] 2017-12-14 18:58
Hi Dan, 
I found some time to replcate some test in our dev environment, and I can simulate the problem, that is still there !
please find attached CSV

[tutorial.tar.gz](https://github.com/cgrates/cgrates/files/1560382/tutorial.tar.gz)

**Comment by danbogos** [comment] 2017-12-15 09:12
Hi @paolovisintin 

Thanks for the files. Can you please send me some sample of RPC call also?

Thanks,
DanB

**Comment by paolovisintin** [comment] 2017-12-15 11:39
Hi @danbogos , yes of course, find below: 
```
root@billing-ral-675f5bd68b-p2885:~# ngrep -W byline port 2012
interface: eth0 (10.32.0.0/255.240.0.0)
filter: (ip or ip6) and ( port 2012 )
#############
T 10.32.0.1:46864 -> 10.32.0.43:2012 [AP]
{"method":"Responder.GetDerivedMaxSessionTime","params":[{"CGRID":"81e4b9558264c002ac8032112a606edc1f11f2a2","RunID":"","OrderID":0,"OriginHost":"127.0.0.1","Source":"KAMAILIO_CGR_AUTH_REQUEST","OriginID":";","ToR":"*voice","RequestType":"*prepaid","Tenant":"evox.it","Category":"call","Account":"0409811201","Subject":"0409811201","Destination":"0039040123123123","SetupTime":"2017-12-15T11:33:16Z","AnswerTime":"0001-01-01T00:00:00Z","Usage":0,"ExtraFields":{"cgr_computelcr":"true","tr_index":"21508","tr_label":"886657091"},"ExtraInfo":"","Partial":false,"Rated":false,"CostSource":"","Cost":-1,"CostDetails":null}],"id":7}

#
T 10.32.0.43:2012 -> 10.32.0.1:46864 [AP]
{"id":7,"result":null,"error":"ACCOUNT_NOT_FOUND"}

##
T 10.32.0.1:46864 -> 10.32.0.43:2012 [AP]
{"method":"Responder.GetLCR","params":[{"Direction":"*out","Category":"call","Tenant":"evox.it","Subject":"0409811201","Account":"0409811201","Destination":"0039040123123123","TimeStart":"2017-12-15T11:33:16Z","TimeEnd":"2017-12-15T11:34:16Z","LoopIndex":0,"DurationIndex":0,"FallbackSubject":"","RatingInfos":null,"Increments":null,"TOR":"","ExtraFields":null,"MaxRate":0,"MaxRateUnit":0,"MaxCostSoFar":0,"CgrID":"81e4b9558264c002ac8032112a606edc1f11f2a2","RunID":"","ForceDuration":false,"PerformRounding":false,"DryRun":false,"DenyNegativeAccount":false}],"id":8}

#
T 10.32.0.43:2012 -> 10.32.0.1:46864 [AP]
{"id":8,"result":{"Entry":{"DestinationId":"*any","RPCategory":"000-LCR-NOSAT","Strategy":"*lowest_cost","StrategyParams":"","Weight":10},"SupplierCosts":[{"Supplier":"*out:evox.it:000-LCR-NOSAT:carrier1.cloud.evox.it","Cost":0.1002,"Duration":60000000000,"Error":"","QOS":null},{"Supplier":"*out:evox.it:000-LCR-NOSAT:carrier2.cloud.evox.it","Cost":0.1998,"Duration":60000000000,"Error":"","QOS":null}]},"error":null}

#^Cexit
18 received, 0 dropped
```

and also SM comunication
```
# ngrep -W byline -d lo port 8448
interface: lo (127.0.0.0/255.0.0.0)
filter: (ip or ip6) and ( port 8448 )
#
T 127.0.0.1:8448 -> 127.0.0.1:36592 [AP]
260:{"event":"CGR_AUTH_REQUEST",
.."tr_index":"42140",
.."tr_label":"1350037412",
.."cgr_reqtype":"*prepaid",
.."cgr_tenant":"evox.it",
.."cgr_account":"0409811201",
.."cgr_destination":"0039040123123123",
.."cgr_setuptime":"1513337880",
.."cgr_computelcr":"true"},
#
T 127.0.0.1:36592 -> 127.0.0.1:8448 [AP]
236:{"Event":"CGR_AUTH_REPLY","TransactionIndex":42140,"TransactionLabel":1350037412,"MaxSessionTime":0,"Suppliers":"carrier1.cloud.evox.it,carrier2.cloud.evox.it","ResourceAllocated":true,"AllocationMessage":"","Error":"ACCOUNT_NOT_FOUND"},
#^Cexit
6 received, 0 dropped
```

**Comment by danbogos** [comment] 2018-01-27 12:56
Hi @paolovisintin 

Have added support for attributes now in KamailioAgent. Please review it and let me know if still problems. Aliases should work too.

DanB

**Comment by paolovisintin** [comment] 2018-01-27 12:58
Hi @danbogos I'll test asap and let you know!

**Comment by danbogos** [comment] 2018-02-12 16:20
hey @paolovisintin 

Can you confirm about closing the issue?

Ta,
DanB

**Comment by miromiky** [comment] 2018-02-13 08:56
Hi Dan, I try to use Attributes.csv which replaces the Aliases.csv,
but have this error: "id":0,"result":null,"error":"rpc: can't find service AttributeSv1.ProcessEvent"



#Tenant,ID,Contexts,FilterIDs,ActivationInterval,FieldName,Initial,Substitute,Append,Weight
miro.it,ATTR_4,*rating,*string:Account:0409811101,2014-01-14T00:00:00Z,Account,*any,04098111,false,10
miro.it,ATTR_4,,,,Subject,*any,0409811101,true,


root@router-864db5cb65-xh6k6:/# ngrep -W byline -d any port 2012
interface: any
filter: (ip or ip6) and ( port 2012 )
#
T 10.32.1.242:58168 -> 10.103.188.58:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"Tenant":"miro.it","ID":"ee01ecc","Context":"*sessions","Time":"2018-02-13T08:50:59Z","Event":{"Account":"0409811101","Destination":"0039040123123","RequestType":"*prepaid","SetupTime":"1518511859","Tenant":"miro.it"}}],"id":0}

##
T 10.103.188.58:2012 -> 10.32.1.242:58168 [AP]
{"id":0,"result":null,"error":"rpc: can't find service AttributeSv1.ProcessEvent"}

########
T 10.32.1.242:58404 -> 10.103.188.58:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"Tenant":"miro.it","ID":"ee01ecc","Context":"*sessions","Time":"2018-02-13T08:50:59Z","Event":{"Account":"0409811101","Destination":"0039040123123","RequestType":"*prepaid","SetupTime":"1518511859","Tenant":"miro.it"}}],"id":0}

##
T 10.103.188.58:2012 -> 10.32.1.242:58404 [AP]
{"id":0,"result":null,"error":"rpc: can't find service AttributeSv1.ProcessEvent"}

##
T 10.32.1.242:58404 -> 10.103.188.58:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"Tenant":"miro.it","ID":"f16a4c1","Context":"*sessions","Time":"2018-02-13T08:50:59Z","Event":{"Account":"0409811101","Destination":"0039040123123","RequestType":"*prepaid","SetupTime":"1518511859","Tenant":"miro.it"}}],"id":1}

#
T 10.103.188.58:2012 -> 10.32.1.242:58404 [AP]
{"id":1,"result":null,"error":"rpc: can't find service AttributeSv1.ProcessEvent"}

########
T 10.32.1.242:58414 -> 10.103.188.58:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"Tenant":"miro.it","ID":"f16a4c1","Context":"*sessions","Time":"2018-02-13T08:50:59Z","Event":{"Account":"0409811101","Destination":"0039040123123","RequestType":"*prepaid","SetupTime":"1518511859","Tenant":"miro.it"}}],"id":0}

##
T 10.103.188.58:2012 -> 10.32.1.242:58414 [AP]
{"id":0,"result":null,"error":"rpc: can't find service AttributeSv1.ProcessEvent"}

#


miro@dev01 ~> kxc router router-sm
root@router-864db5cb65-xh6k6:/# ngrep -W byline -d any port 8448
interface: any
filter: (ip or ip6) and ( port 8448 )
#
T 127.0.0.1:8448 -> 127.0.0.1:55888 [AP]
280:{"event":"CGR_AUTH_REQUEST",
.."tr_index":"37392",
.."tr_label":"1610454374",
.."cgr_subsystems":"*attributes;*resources;*accounts;*suppliers",
.."RequestType":"*prepaid",
.."Tenant":"miro.it",
.."Account":"0409811101",
.."Destination":"0039040123123",
.."SetupTime":"1518511859"},
##
T 127.0.0.1:55888 -> 127.0.0.1:8448 [AP]
231:{"Event":"CGR_AUTH_REPLY","TransactionIndex":"37392","TransactionLabel":"1610454374","Attributes":"","ResourceAllocation":"","MaxUsage":0,"Suppliers":"","Error":"ATTRIBUTES_ERROR: rpc: can't find service AttributeSv1.ProcessEvent"},
##
T 127.0.0.1:8448 -> 127.0.0.1:55888 [AP]
280:{"event":"CGR_AUTH_REQUEST",
.."tr_index":"37392",
.."tr_label":"1610454374",
.."cgr_subsystems":"*attributes;*resources;*accounts;*suppliers",
.."RequestType":"*prepaid",
.."Tenant":"miro.it",
.."Account":"0409811101",
.."Destination":"0039040123123",
.."SetupTime":"1518511859"},
#
T 127.0.0.1:55888 -> 127.0.0.1:8448 [AP]
231:{"Event":"CGR_AUTH_REPLY","TransactionIndex":"37392","TransactionLabel":"1610454374","Attributes":"","ResourceAllocation":"","MaxUsage":0,"Suppliers":"","Error":"ATTRIBUTES_ERROR: rpc: can't find service AttributeSv1.ProcessEvent"},
#

**Comment by TeoV** [comment] 2018-02-13 09:25
Hi miromiky ,
For me it works .
Here is what I did :
1)Start the engine with a custom configuration (tutmysql from our sample)
cgr-engine -config_dir=/usr/share/cgrates/conf/samples/tutmysql
2) Load the data with cgr-loader : 
cgr-loader -datadb_host "127.0.0.1" -datadb_name "10" -datadb_port "6379" -datadb_type "redis" -datadb_user "cgrates" -verbose
And check the data and the indexes 
2018/02/13 11:09:38 AttributeProfiles:
2018/02/13 11:09:38 	miro.it:ATTR_4
2018/02/13 11:09:38 Indexing Attribute Profiles
2018/02/13 11:09:38 Tenant:Context  miro.it:*rating, keys [*string:Account:0409811101]
2018/02/13 11:09:38 Tenant:Context  miro.it:*rating, keys [ATTR_4]
3)Send the command via telnet :
{"method":"AttributeSv1.ProcessEvent","params":[{"Tenant":"miro.it","ID":"ee01ecc","Context":"*sessions","Time":"2018-02-13T08:50:59Z","Event":{"Account":"0409811101","Destination":"0039040123123","RequestType":"*prepaid","SetupTime":"1518511859","Tenant":"miro.it"}}],"id":0}
4)Capture the result with ngrep : 
####
T 2018/02/13 11:20:54.472485 ::1:36362 -> ::1:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"Tenant":"miro.it","ID":"ee01ecc","Context":"*sessions","Time":"2018-02-13T08:50:59Z","Event":{"Account":"0409811101","Destination":"0039040123123","RequestType":"*prepaid","SetupTime":"1518511859","Tenant":"miro.it"}}],"id":0}.

##
T 2018/02/13 11:20:54.472808 ::1:2012 -> ::1:36362 [AP]
{"id":0,"result":null,"error":"NOT_FOUND"}

I get this error because I don't have all the data , but the conclusion is it works.
Verify your config and make shure you active this service : 
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/tutmysql/cgrates.json#L129

Thanks,
TeoV

**Comment by miromiky** [comment] 2018-02-13 09:58
Hi TeoV, :) 

This is my configuration now:

sm:
```
"attributes_conns": [
   {"address": "billing-ral-service:2012", "transport": "*json"}
],
```
ral:
```
"attributes": {
   "enabled": true
},
```

The account 0409811101 is under aliases 04098111
In Cgrates i not need to create account 0409811101 right? because when i call with account 0409811101 
He use aliases account configuration (04098111) right?

So i create just 04098111 account in cgrates:

Attributes.csv
```
#Tenant,ID,Contexts,FilterIDs,ActivationInterval,FieldName,Initial,Substitute,Append,Weight
miro.it,ATTR_4,*rating,*string:Account:0409811101,2014-01-14T00:00:00Z,Account,*any,04098111,false,10
miro.it,ATTR_4,,,,Subject,*any,0409811101,true,
```
RatingProfiles.csv
```
#Direction,Tenant,Category,Subject,ActivationTime,RatingPlanId,RatesFallbackSubject,CdrStatQueueIds
*out,miro.it,call,04098111,2014-01-14T00:00:00Z,RP_ALIAS,,
```
RatingPlans.csv
```
#Id,DestinationRatesId,TimingTag,Weight
RP_ALIAS,DR_ALIAS,*any,10.00

DestinationRates.csv
#Id,DestinationId,RatesTag,RoundingMethod,RoundingDecimals,MaxCost,MaxCostStrategy
DR_ALIAS,DST_ITA_FIX,RT_0CNT,*up,4,0,
```
Destination.csv
```
#Id,Prefix
DST_ITA_FIX,003904
```
Rates.csv
```
#Id,ConnectFee,Rate,RateUnit,RateIncrement,GroupIntervalStart
RT_0CNT,0.0000,0.0000,60s,1s,0s
```

AccountAction.csv:
```
#Tenant,Account,ActionPlanId,ActionTriggersId,AllowNegative,Disabled
miro.it,04098111,PACKAGE_10,,0,
```
ActionPlans.csv
```
#Id,ActionsId,TimingId,Weight
PACKAGE_10,TOPUP_RST_10,*asap,10
```

Actions.csv
```
#ActionsId[0],Action[1],ExtraParameters[2],Filter[3],BalanceId[4],BalanceType[5],Directions[6],Categories[7],DestinationIds[8],RatingSubject[9],SharedGroup[10],ExpiryTime[11],TimingIds[12],Units[13],BalanceWeight[14],BalanceBlocker[15],BalanceDisabled[16],Weight[17]
TOPUP_RST_10,*topup_reset,,,,*monetary,*out,,*any,,,*unlimited,,1,10,false,false,10
```



cgr-load..
```
2018/02/13 09:54:36 AttributeProfiles:
2018/02/13 09:54:36 	miro.it:ATTR_4
2018/02/13 09:54:36 Tenant:Context  miro.it:*rating, keys [*string:Account:0409811101]
2018/02/13 09:54:36 Tenant:Context  miro.it:*rating, keys [ATTR_4]
```

But when i start the call with 0409811101 this is teh log now:


root@router-864db5cb65-4f75s:/# ngrep -W byline -d any port 2012
interface: any
filter: (ip or ip6) and ( port 2012 )
#
T 10.32.1.246:33542 -> 10.103.188.58:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"Tenant":"miro.it","ID":"e4495e7","Context":"*sessions","Time":"2018-02-13T09:53:04Z","Event":{"Account":"0409811101","Destination":"0039040123123","RequestType":"*prepaid","SetupTime":"1518515584","Tenant":"miro.it"}}],"id":0}

##
T 10.103.188.58:2012 -> 10.32.1.246:33542 [AP]
{"id":0,"result":null,"error":"NOT_FOUND"}

##
T 10.32.1.246:33536 -> 10.103.188.58:2012 [AP]
{"method":"Responder.GetDerivedMaxSessionTime","params":[{"CGRID":"da39a3ee5e6b4b0d3255bfef95601890afd80709","RunID":"","OrderID":0,"OriginHost":"","Source":"SMG_","OriginID":"","ToR":"*voice","RequestType":"*prepaid","Tenant":"miro.it","Category":"call","Account":"0409811101","Subject":"","Destination":"0039040123123","SetupTime":"2018-02-13T09:53:04Z","AnswerTime":"0001-01-01T00:00:00Z","Usage":0,"ExtraFields":{},"ExtraInfo":"","Partial":false,"Rated":false,"CostSource":"","Cost":-1,"CostDetails":null}],"id":0}

##
T 10.103.188.58:2012 -> 10.32.1.246:33536 [AP]
{"id":0,"result":null,"error":"ACCOUNT_NOT_FOUND"}

##
T 10.32.1.246:33542 -> 10.103.188.58:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"Tenant":"miro.it","ID":"dcd6a23","Context":"*sessions","Time":"2018-02-13T09:53:05Z","Event":{"Account":"0409811101","Destination":"0039040123123","RequestType":"*prepaid","SetupTime":"1518515585","Tenant":"miro.it"}}],"id":1}

#
T 10.103.188.58:2012 -> 10.32.1.246:33542 [AP]
{"id":1,"result":null,"error":"NOT_FOUND"}

##
T 10.32.1.246:33536 -> 10.103.188.58:2012 [AP]
{"method":"Responder.GetDerivedMaxSessionTime","params":[{"CGRID":"da39a3ee5e6b4b0d3255bfef95601890afd80709","RunID":"","OrderID":0,"OriginHost":"","Source":"SMG_","OriginID":"","ToR":"*voice","RequestType":"*prepaid","Tenant":"miro.it","Category":"call","Account":"0409811101","Subject":"","Destination":"0039040123123","SetupTime":"2018-02-13T09:53:05Z","AnswerTime":"0001-01-01T00:00:00Z","Usage":0,"ExtraFields":{},"ExtraInfo":"","Partial":false,"Rated":false,"CostSource":"","Cost":-1,"CostDetails":null}],"id":1}

#
T 10.103.188.58:2012 -> 10.32.1.246:33536 [AP]
{"id":1,"result":null,"error":"ACCOUNT_NOT_FOUND"}

#


root@router-864db5cb65-4f75s:/# ngrep -W byline -d any port 8448
interface: any
filter: (ip or ip6) and ( port 8448 )
#
T 127.0.0.1:8448 -> 127.0.0.1:52948 [AP]
279:{"event":"CGR_AUTH_REQUEST",
.."tr_index":"18571",
.."tr_label":"914374647",
.."cgr_subsystems":"*attributes;*resources;*accounts;*suppliers",
.."RequestType":"*prepaid",
.."Tenant":"miro.it",
.."Account":"0409811101",
.."Destination":"0039040123123",
.."SetupTime":"1518515584"},
##
T 127.0.0.1:52948 -> 127.0.0.1:8448 [AP]
192:{"Event":"CGR_AUTH_REPLY","TransactionIndex":"18571","TransactionLabel":"914374647","Attributes":"","ResourceAllocation":"","MaxUsage":0,"Suppliers":"","Error":"RALS_ERROR: ACCOUNT_NOT_FOUND"},
##
T 127.0.0.1:8448 -> 127.0.0.1:52948 [AP]
279:{"event":"CGR_AUTH_REQUEST",
.."tr_index":"18571",
.."tr_label":"914374647",
.."cgr_subsystems":"*attributes;*resources;*accounts;*suppliers",
.."RequestType":"*prepaid",
.."Tenant":"miro.it",
.."Account":"0409811101",
.."Destination":"0039040123123",
.."SetupTime":"1518515585"},
#
T 127.0.0.1:52948 -> 127.0.0.1:8448 [AP]
192:{"Event":"CGR_AUTH_REPLY","TransactionIndex":"18571","TransactionLabel":"914374647","Attributes":"","ResourceAllocation":"","MaxUsage":0,"Suppliers":"","Error":"RALS_ERROR: ACCOUNT_NOT_FOUND"},
#

**Comment by miromiky** [comment] 2018-02-13 11:13
TeoV,
I put Contexts *sessions and Subject,*any,04098111 ,The attributes pass! :) 

Attributes.csv
```
#Tenant,ID,Contexts,FilterIDs,ActivationInterval,FieldName,Initial,Substitute,Append,Weight
miro.it,ATTR_4,*sessions,*string:Account:0409811101,2014-01-14T00:00:00Z,Account,*any,04098111,false,10
miro.it,ATTR_4,,,,Subject,*any,04098111,true,
```
Unfortunately there is not even a documentation on the Attributes, and I have to go to the intuition :)
I still test and let you know if everything is ok...

**Comment by danbogos** [comment] 2018-02-13 12:09
hi @miromiky 

This appears as a misconfiguration. Please address the requests for help over google group so others can also benefit out of answers there. We use github issues for feature requests/bug reports.

Ta,
DanB

**Closed by danbogos** 2018-02-13 12:09 UTC

**Comment by miromiky** [comment] 2018-02-13 12:33
Hi, Dan 
Ok, no problem, 
I just wanted to tell you that Attributes.csv does not work for me following this config:
https://github.com/cgrates/cgrates/blob/master/data/tariffplans/tutorial/Attributes.csv
Thanks

**Comment by danbogos** [comment] 2018-02-13 12:34
@miromiky 

Try using *any as context.

DanB

**Comment by miromiky** [comment] 2018-02-13 12:41
@danbogos 
I put *any as context
The call start but have this error:
```
##
T 127.0.0.1:8448 -> 127.0.0.1:52948 [AP]
315:{"event":"CGR_CALL_START",
.."h_entry":"1097",
.."h_id":"10523",
.."cgr_subsystems":"*resources;*accounts",
.."OriginID":"OGM1MmViMzNhM2ZkZjYyNzEwM2IwY2Q4OGVhMDlkMDg.;5e53430c",
.."RequestType":"*prepaid",
.."Tenant":"miro.it",
.."Account":"0409811101",
.."Destination":"0039040123123",
.."AnswerTime":"1518525400"},
#
T 127.0.0.1:52948 -> 127.0.0.1:8448 [AP]
92:{"Event":"CGR_SESSION_DISCONNECT","HashEntry":"","HashId":"","Reason":"INSUFFICIENT_CREDIT"},
##
```

**Comment by danbogos** [comment] 2018-02-13 12:42
OK, let's continue on google group in that case.

DanB

**Comment by miromiky** [comment] 2018-02-13 12:44
Yes Sir, i create the topic.

**Comment by miromiky** [comment] 2018-02-13 12:51
@danbogos 
SOLVED :)
just add *attributes in route(CGR_CALL_START)
`\"cgr_subsystems\":\"*attributes;*resources;*accounts\",`

**Comment by danbogos** [comment] 2018-02-13 12:53
Great, thanks for reporting!
