### ISSUE TITLE
Freeswitch Agent didn't try to reconnect to Freeswitch with headers reading error.

### ISSUE THREAD

**Issue by ruhnet** [cgrates/cgrates#3794] opened 2022-11-24 20:00 UTC
I'm on master branch. (My config file is attached.) A few days ago I noticed we must have had a temporary network connection error between CGRateS and Freeswitch (they are in separate DCs), and these were in the log file:

<FSock> Error reading headers: <read tcp 172.20.223.41:40368->172.20.223.24:8021: read: connection timed out>
    <FSock> Disconnecting from FreeSWITCH!
    <FSock> Error reading headers: <read tcp 172.20.223.41:40362->172.20.223.24:8021: read: connection timed out>
    <FSock> Disconnecting from FreeSWITCH!

After the second disconnect, no reconnection attempt was made, even though the network was restored, and CGRateS had to be restarted. When restarted it connected back up as normal.

My FS agent reconnection attempts are set to -1 in the config file, which is supposed to be unlimited.

So, I'm wondering why the reconnection attempt was abandoned?

Please let me know anything I can do to assist in diagnosing.

[cgrates.json.txt](https://github.com/cgrates/cgrates/files/10087055/cgrates.json.txt)

**Comment by porosnicuadrian** [comment] 2022-11-25 07:58
Hi @ruhnet,

Please, can you tell me what you did in order to get this error first?
"read tcp 172.20.223.41:40368->172.20.223.24:8021: read: connection timed out"

Thanks,
Adrian

**Comment by ruhnet** [comment] 2022-11-25 19:47
@porosnicuadrian There was a network error or loss of connectivity between my CGRateS server and Freeswitch (they are in different data centers). I'm not exactly sure of the style of network problem (high latency, packet loss, etc.) since I didn't notice it until after the network was working fine again, but calls had stopped processing. I wasn't doing anything on the system at the time it happened---in other words I wasn't changing anything or making API calls to CGRateS.
My log level is on debug, and there were no other log messages of note. Calls were processing fine until the network issue, and I thought the Freeswitch agent would have tried to reconnect when the network was restored, but it did not.

**Comment by porosnicuadrian** [comment] 2022-11-28 14:57
Hi @ruhnet 

I tried to reproduce the issue on my side, and the error that I received from losing the connection between CGRates and Freeswitch was "EOF"(end of file), and this error will lead cgrates to reconnect until the connection is established again. To check better this problem, can you please instruct us how to reproduce your error?

Thanks,
@porosnicuadrian

**Comment by ruhnet** [comment] 2022-11-28 17:11
Well, I guess I'll have to see if it happens again. As I said I don't know exactly the state of things right when it occurred. Everything has been running fine since, so I'm not sure how to reproduce it. If it does happen again I will try to take a detailed look at the logs to see the exact communication and call state at the time to see if there's any way it can be reproduced.

**Comment by ruhnet** [comment] 2022-12-08 16:21
@porosnicuadrian well, it just happened again---this time I was watching the system, but unfortunately I didn't have any packet capture going at the time. (Would be difficult to leave packet capture running 24/7 for 10 days haha.)
I believe the issue happens when there is a network error _while data is being transferred via FS event socket_ and it's only then that CGRateS fails to reconnect. There was an active call placed, and during call setup, evidently the network had a blip, and CGRateS log gave the same output as in my first message, and then just sat there and did not attempt to reconnect to Freeswitch. When network errors occurred at other times, between event socket data exchange, the FS agent reconnected as normal.
So I'm still not positive exactly how to reproduce this, but it seems it is indeed a code issue of some kind rather than just a one-time fluke.

**Comment by ruhnet** [comment] 2022-12-08 17:29
I'm not really familiar enough with the FS socket library to know for sure, but looking through the code it looks like maybe a `ReconnectIfNeeded()` should be used here instead of a disconnect, or after the `Disconnect()` possibly?
https://github.com/cgrates/fsock/blob/1e3fb3cc7c8e4cd3360f52a268b67c8e3c068f61/fsock.go#L299

**Comment by porosnicuadrian** [comment] 2022-12-09 09:44
Hello @ruhnet,

The thing is that we do a ``ReconnectIfNeeded()`` only if the error is EOF(end of file), and this happen when no more input is available. This means, in your case, the error "read: connection timed out" will not produce that and that's how we implement it,
I'm sorry about that but we do really need the way of how to reproduce that error of connection timed out" :(.

Thanks,
@porosnicuadrian

**Comment by danbogos** [comment] 2023-01-13 15:44
Hi @ruhnet 

Please retest with the latest master since this issue should be fixed there.

Thanks,
DanB

**Closed by danbogos** 2023-01-13 15:44 UTC

**Comment by ruhnet** [comment] 2023-01-14 15:08
I will upgrade to latest master. Thanks!!
