### ISSUE TITLE
Diameter Agent Support for Messages Other Than CCR/A/T

### ISSUE THREAD

**Issue by uppaljs** [cgrates/cgrates#821] opened 2017-11-16 04:07 UTC
Hi,

Please add support for generic messages in the diameter agent. Currently only CCR/A/T are used.

For 3GPP Gy, below is a list of messages

CER, CEA, DWR and DWA is already sent by the library automatically.

Message | Direction | Function
-- | -- | --
CCR | P-GW->OCS | Requests credits for the request service.
CCA | OCS->P-GW | Returns the request result of the CCR message.
RAR | OCS->P-GW | Requests the re-authentication or authorization service for users.
RAA | P-GW->OCS | Returns the request result of the RAR message.
ASR | OCS->P-GW | Requests the session identified by the Session-Id be stopped.
ASA | P-GW->OCS | Returns the request result of the ASR message.
DPR | P-GW->OCS | Informs its intentions to shutdown the transport connection to the peer.
DPA | OCS->P-GW | Returns the request result of the DPR message.
CER | P-GW->OCS | Exchange local capabilities.
CEA | OCS->P-GW | Returns the request result of the CER message.
DWR | P-GW->OCS | heart check.
DWA | OCS->P-GW | Returns the request result of the DWR message.

**Comment by decsiteru** [comment] 2018-07-10 00:30
Any news on this issue? 
We're looking for a charging system with a new setup which is only compatible with Ro/Gy

**Comment by danbogos** [comment] 2018-07-10 06:58
hey @decsiteru 

The issue is still in our plans, let's just say we could not find any of our customers serious enough about it. 
Now that we have the new HTTPAgent infrastructure, cloning that to Diameter should be fairly easy. Let's just aim it for the next weeks or so.

DanB

**Comment by decsiteru** [comment] 2018-07-11 21:53
Excellent news, thanks for the quick reply.

For the record, the setup on our side is not ready yet (it will be in a few months) but we're looking forward to testing CGrates when the time comes.

**Comment by danbogos** [comment] 2018-08-30 14:54
hey @uppaljs 

We have finally reached this task, sorry for delay.

If by any chance you can send us some .pcap samples with messages which are not parsed by CGRateS, it will be great since we can integrate them into our build tests.

Ta,
DanB

**Closed** 2018-10-05 12:16 UTC
