### ISSUE TITLE
Error executing command: SERVER_ERROR: unexpected EOF

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#1194] opened 2018-09-04 19:30 UTC
Dear Team,

I have noticed this error while testing latest master code some minutes ago.

I am using MongoDB and I cleaned all data from my MongoDB before loading the tutorial files from cgrates/data/tariffplans/tutorial/ folder.

cgr-console 'cost Category="call" Tenant="cgrates.org" Subject="1001" Destination="1002" AnswerTime="2014-08-04T13:00:00Z" Usage="20s"'

result : **Error executing command: SERVER_ERROR: unexpected EOF**

Commands run in console ---> https://pastebin.com/C2aH8gTb

sniffing with ngrep on 2012 port ----> https://pastebin.com/2dAGMRgD

Before running the commands above I run the migrator command first and received : 
2018/09/04 22:13:11 Data migrated: map[]

Best Regards

Vasilios Tzanoudakis

**Comment by TeoV** [comment] 2018-09-05 07:00
Hi @vtzan 
I wasn't able to reproduce your problem :( Here is what I tried to do : 
1) Start with a fresh database
2) When I tried to start the engine I get an error and it's normal because engine complain about versions. 
```
teo@teo:~$ cgr-engine -config_dir=/usr/share/cgrates/conf/samples/tutmongo
Migration needed: please backup cgrates data and run : <cgr-migrator>
```
3) To fix this you will have to set the versions using cgr-migrator : 
```
teo@teo:~$ cgr-migrator -migrate="*set_versions" -config_dir=/usr/share/cgrates/conf/samples/tutmongo
```
4) After that I load the data with cgr-loader : 
```
teo@teo:~$ cgr-loader -config_dir=/usr/share/cgrates/conf/samples/tutmongo -verbose -path=/usr/share/cgrates/tariffplans/tutorial
```
5) Verify if accounts was created and execute your command : 
https://pastebin.com/Fz0Anxim

As you see for me it works. 
Here is my vesion : 
```
teo@teo:~$ cgr-engine -version
CGRateS 0.9.1~rc8 git+e3086a6 (2018-09-03T10:29:44-04:00)
```
I will close this issue now and if you still get the error please reopen this and told us exactly step by step how to reproduce it 

Thanks,
TeoV

**Closed by TeoV** 2018-09-05 07:00 UTC

**Comment by vtzan** [comment] 2018-09-05 14:27
Hi @TeoV 

Thank you for your fast  response. The error had to do with my modified cgrates.json config file which used to work 1 month ago. I tried the one on the samples and the error disappeared. 
I will now check all the parameters one by one.

Best Regards
