### ISSUE TITLE
Issues with *topup_reset 

### ISSUE THREAD

**Issue by eloycoto** [cgrates/cgrates#556] opened 2016-09-29 16:27 UTC
Hey @danbogos ,

I've just struggled with AccountActions. I have my action defined like this on postgres:

```
=> select * from tp_actions where id=4;
─[ RECORD 1 ]────┬──────────────────────────────
id               │ 4
tpid             │ tptest
tag              │ NEW_CUSTOMER_102
action           │ *topup_reset
balance_tag      │
balance_type     │ *monetary
directions       │ *out
units            │ 500.00
expiry_time      │ *unlimited
timing_tags      │ *asap
destination_tags │ *any
rating_subject   │
categories       │
shared_groups    │
balance_weight   │ 10
balance_disabled │
extra_parameters │
weight           │ 10.00
balance_blocker  │
filter           │
created_at       │ 2016-09-29 16:09:42.510729+00
```

After read the database, my cdr-console actions look like this:

```
 "NEW_CUSTOMER_102": [
  {
   "Id": "NEW_CUSTOMER_102",
   "ActionType": "*topup_reset",
   "ExtraParameters": "",
   "Filter": "",
   "ExpirationString": "*unlimited",
   "Weight": 10,
   "Balance": {
    "Uuid": null,
    "ID": null,
    "Type": "*monetary",
    "Value": {
     "Method": "",
     "Params": null,
     "Static": 500
    },
    "Directions": {
     "*out": true
    },
    "ExpirationDate": null,
    "Weight": 10,
    "DestinationIDs": null,
    "RatingSubject": null,
    "Categories": null,
    "SharedGroups": null,
    "TimingIDs": {
     "*asap": true
    },
    "Timings": [
     {
      "Years": [],
      "Months": [],
      "MonthDays": [],
      "WeekDays": [],
      "StartTime": "*asap",
      "EndTime": ""
     }
    ],
    "Disabled": null,
    "Factor": null,
    "Blocker": null
   }
  }
 ],
```

The logs say that action is executed:

```
Sep 29 17:10:26  CGRateS[2663]: <Scheduler> executing task NEW_CUSTOMER_102 on account
```

But the account didn't update. Any insight with this?

```
[
 {
  "ID": "tptest:102",
  "BalanceMap": {
   "*monetary": [
    {
     "Uuid": "9c624969-aec3-48af-beb4-a68cf83e5774",
     "ID": "",
     "Value": 0,
     "Directions": {},
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 10,
     "DestinationIDs": {},
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    }
   ]
  },
  "UnitCounters": null,
  "ActionTriggers": [ ],
  "AllowNegative": false,
  "Disabled": false
 }
]
```

Any idea?
Regards.

PS: Running in the lastest master.

**Comment by danbogos** [comment] 2016-09-29 16:51
Hey Eloy

I can check it when back but till then you can try playing with your
filters since I am sure they don't much with your account somehow.

DanB

Am 29.09.2016 9:27 AM schrieb "Eloy Coto" <notifications@github.com>:

Hey @danbogos <https://github.com/danbogos> ,

I've just struggled with AccountActions. I have my action defined like this
on postgres:

=> select * from tp_actions where id=4;
─[ RECORD 1 ]────┬──────────────────────────────
id               │ 4
tpid             │ tptest
tag              │ NEW_CUSTOMER_102
action           │ *topup_reset
balance_tag      │
balance_type     │ *monetary
directions       │ *out
units            │ 500.00
expiry_time      │ *unlimited
timing_tags      │ *asap
destination_tags │ *any
rating_subject   │
categories       │
shared_groups    │
balance_weight   │ 10
balance_disabled │
extra_parameters │
weight           │ 10.00
balance_blocker  │
filter           │
created_at       │ 2016-09-29 16:09:42.510729+00

After read the database, my cdr-console actions look like this:

 "NEW_CUSTOMER_102": [
  {
   "Id": "NEW_CUSTOMER_102",
   "ActionType": "*topup_reset",
   "ExtraParameters": "",
   "Filter": "",
   "ExpirationString": "*unlimited",
   "Weight": 10,
   "Balance": {
    "Uuid": null,
    "ID": null,
    "Type": "*monetary",
    "Value": {
     "Method": "",
     "Params": null,
     "Static": 500
    },
    "Directions": {
     "*out": true
    },
    "ExpirationDate": null,
    "Weight": 10,
    "DestinationIDs": null,
    "RatingSubject": null,
    "Categories": null,
    "SharedGroups": null,
    "TimingIDs": {
     "*asap": true
    },
    "Timings": [
     {
      "Years": [],
      "Months": [],
      "MonthDays": [],
      "WeekDays": [],
      "StartTime": "*asap",
      "EndTime": ""
     }
    ],
    "Disabled": null,
    "Factor": null,
    "Blocker": null
   }
  }
 ],

The logs say that action is executed:

Sep 29 17:10:26  CGRateS[2663]: <Scheduler> executing task
NEW_CUSTOMER_102 on account

But the account didn't update. Any insight with this?

[
 {
  "ID": "tptest:102",
  "BalanceMap": {
   "*monetary": [
    {
     "Uuid": "9c624969-aec3-48af-beb4-a68cf83e5774",
     "ID": "",
     "Value": 0,
     "Directions": {},
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 10,
     "DestinationIDs": {},
     "RatingSubject": "",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": null,
     "Blocker": false
    }
   ]
  },
  "UnitCounters": null,
  "ActionTriggers": [ ],
  "AllowNegative": false,
  "Disabled": false
 }
]

Any idea?
Regards.

PS: Running in the lastest master.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cgrates/cgrates/issues/556>, or mute the thread

**Comment by danbogos** [comment] 2016-11-29 11:22
hey @eloycoto 

Not sure we left this one, but is it still active for you? 

Thanks,
DanB

**Comment by eloycoto** [comment] 2016-11-29 11:25
Hey @danbogos 

Yes, it's still an issue. With the master on the commit ce23852583e59b3274228bd6535a68e9a1ba05b5. 

Regards.

**Comment by TeoV** [comment] 2019-06-20 09:56
Hi @eloycoto,

We tried to reproduce this but without success.
We will close this issue now and in case that you have a problem with the latest master please update a new one.

Thanks,
TeoV

**Closed by TeoV** 2019-06-20 09:56 UTC
Labels: in progress
