### ISSUE TITLE
CGrates crashing (Package 15th Dec 2015)

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#351] opened 2016-01-08 07:36 UTC
Hi Guys,

For the last few days we seem to have an issue with CGRates crashing at a certain time of the day.  I tried everything possible that I could think of to resolve the issue including increasing the file descriptors etc without success.  

Attached is the strace.

root@bill:~# ls -l /usr/bin/ | grep cgr
-rwxr-xr-x 1 root   root    13164608 Dec 16 00:30 cgr-console
-rwxr-xr-x 1 root   root    17485600 Dec 16 00:30 cgr-engine
-rwxr-xr-x 1 root   root    14410048 Dec 16 00:30 cgr-loader
-rwxr-xr-x 1 root   root    13463872 Dec 16 00:30 cgr-tester

root@bill:~# ulimit -n (Openfiles)
262144

root@bill:~# more /proc/sys/fs/file-nr
2720	0	2009452

OS: Debian Jessie 8.2
CPU: 11 CPU Cores
Ram: 19G Ram

[cgrates.txt](https://github.com/cgrates/cgrates/files/82308/cgrates.txt)

Regards,

Errol

**Comment by danbogos** [comment] 2016-01-08 08:37
Hey @ewsamuels 

I have just built another .deb out of today's master. Please test with that one and report back.

Thanks,
DanB

**Comment by ewsamuels** [comment] 2016-01-08 09:07
Hi DanB,
Thanks for your quick response as usual.
Do I need to make any database changes for this new package?

**Comment by danbogos** [comment] 2016-01-08 10:06
Hi Errol,

Yes, please use create_cdrs.sql script for that.

DanB

**Comment by ewsamuels** [comment] 2016-01-08 13:24
Hi DanB,
Out of curiosity what was the issue?
Thanks
Errol

**Comment by danbogos** [comment] 2016-01-08 14:36
Hi @ewsamuels 

That is the good question. If you find the answer would love to hear it also :).

I have seen this issue in the past but then it disappeared in time. This can be due to either go upgrade (used to compile the .deb package) or debian itself.

That is why I need you to run the same versions as us before jumping into conclusions.

Thanks,
DanB

**Comment by danbogos** [comment] 2016-01-19 09:38
Hi @ewsamuels 

please confirm if the issue is there after upgrading.

Ta,
DanB

**Comment by danbogos** [comment] 2016-01-24 15:02
Closing with invalid due to no feedback from @ewsamuels 

DanB

**Closed by danbogos** 2016-01-24 15:02 UTC
