### ISSUE TITLE
Redis password 

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1236] opened 2018-09-29 13:18 UTC
Hello Dear CGRateS Team!
When redis is using password and the password in the configs is not good for some reason,
 cgr-engine is wrongly prints out that datadb needs migration. That can lead to confusion.
Please put a correct message about access denied or that the password is wrong.
Thanks,
Michael

**Comment by Trial97** [comment] 2018-10-01 08:10
Hello @muxalko,
We could not reproduce the issue. The steps we have followed are\:

1. Setting a password in redis\:
`redis-cli`
`config set requirepass password12345`

2. Using tutmysql configuration we added the line, in the `"data_db"` structure \: 
`"db_password": "password12345",`

3. Starting cgr-engine using the chosen configuration\:
`cgr-engine -config_dir=/usr/share/cgrates/conf/samples/tutmysql`

If the password is wrong in the configuration file the cgr-engine will not start, but will print the following line in syslog \:
`CGRateS <7661d31> [2113]: Could not configure dataDb: ERR invalid password exiting!`

Can you please provide more details so we can reproduce the issue.

Thanks,
Trial97

**Comment by muxalko** [comment] 2018-10-02 16:51
Hello @Trial97 ,
It is nice to meet you.
Yes you are right, if the password is wrong, it prints 
2018/10/02 16:44:12 CGRateS <d82bbbf> [CRITICAL] Could not configure dataDb: ERR invalid password exiting!
Which is correct.
But, when it is missing, the message is wrong
Here is how I reproduce the issue:
my config:
```
{
	"data_db": {
		"db_host": "redis-master.redis",
		"db_name": "0",
		//"db_password": "xxx"
	},

	"rals": {
		"enabled": true,
	}
}
```


Each time I try to run cgr-engine, different migration need is shown: )
```
Migration needed: please backup cgr data and run : <cgr-migrator -migrate=*accounts>
...
Migration needed: please backup cgr data and run : <cgr-migrator -migrate=*action_triggers>
...
Migration needed: please backup cgr data and run : <cgr-migrator -migrate=*shared_groups>
...
```

when I put the correct password, everything works as expected.
Configs:
```
{
	"data_db": {
		"db_host": "redis-master.redis",
		"db_name": "0",
		"db_password": "xxx"
	},

	"rals": {
		"enabled": true,
	}
}
```

Output:
```
2018/10/02 16:33:15 rpc.Register: method "Call" has 4 input parameters; needs exactly three
2018/10/02 16:33:15 CGRateS <3a4bfd3> [INFO] <CDRC> No enabled CDRC clients
2018/10/02 16:33:15 CGRateS <3a4bfd3> [WARNING] WARNING: missing TLS certificate/key file!
2018/10/02 16:33:15 CGRateS <3a4bfd3> [WARNING] WARNING: missing TLS certificate/key file!
2018/10/02 16:33:15 CGRateS <3a4bfd3> [WARNING] WARNING: missing TLS certificate/key file!
2018/10/02 16:33:15 CGRateS <3a4bfd3> [INFO] <HTTP> enabling handler for JSON-RPC
2018/10/02 16:33:15 CGRateS <3a4bfd3> [INFO] <HTTP> enabling handler for WebSocket connections
2018/10/02 16:33:15 CGRateS <3a4bfd3> [INFO] <HTTP> start listening at <:2080>
2018/10/02 16:33:15 CGRateS <3a4bfd3> [INFO] Starting CGRateS JSON server at <:2012>.
2018/10/02 16:33:15 CGRateS <3a4bfd3> [INFO] Starting CGRateS GOB server at <:2013>.

```
Thanks,
Michael

**Comment by Trial97** [comment] 2018-10-03 08:30
Hello @muxalko,
We tried to reproduce the issue as you said, but without success. If the redis server was password-protected, cgr-engine will not start with a configuration that does not have the password set but will print the following message in syslog:

`CGRateS <d4dbb34> [1928]: Could not configure dataDb: NOAUTH Authentication required. exiting!`

Can you please provide us the following information:

- What version of redis do you use?

- How did you set the password for redis?

- What version of cgrates are you using?

Thanks,
Trial97

**Comment by Trial97** [comment] 2018-10-22 11:19
Hey @muxalko,
Short reminder: Have you managed to get the ngrep capture?

Thanks,
Trial97

**Comment by muxalko** [comment] 2018-11-05 16:34
Hello @Trial97 ,
Sorry for the delay.
Actually, I switched to work without a password.
Noticed the same migration needed message is shown whenever redis is not available.
Perhaps that can lead to some clues.

Thanks,
Michael

**Comment by Trial97** [comment] 2018-11-06 12:02
Hey @muxalko,
We have not been able to reproduce the problem so we will close the issue. If the problem persists please reopen it.

Thanks,
Trial97

**Closed by Trial97** 2018-11-06 12:02 UTC
