### ISSUE TITLE
SERVER_ERROR from AttributeS

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1167] opened 2018-08-02 10:28 UTC
Hello Dear CGRateS Team!

The AttributeS module response with SERVER_ERROR when there are no attributes configured:

```
#
T 2018/08/02 11:42:16.797446 127.0.0.1:35774 -> 127.0.0.1:2012 [AP]
{"method":"AttributeSv1.ProcessEvent","params":[{"AttributeIDs":null,"ProcessRuns":null,"Tenant":"golant","ID":"dmt:082b841","Context":"*sessions","Time":"2018-08-02T11:42:16.797133833+03:00","Event":{"Account":"12345","AnswerTime":"2018-08-02 11:42:16 +0300 IDT","Category":"data","Destination":"42502","Direction":"*out","EventName":"DIAMETER_CCR","OriginHost":"GatewayService-4-13-1.PTggsn.telco.net","OriginID":"GatewayService-4-13-1.PTggsn.telco.net;1533199336;167816175","RequestType":"*prepaid","SetupTime":"2018-08-02 11:42:16 +0300 IDT","Subject":"*attributes","Tenant":"golant","ToR":"*data","Usage":"10485760","cgr_flags":"*accounts;*attributes"}}],"id":1}

#
T 2018/08/02 11:42:16.797710 127.0.0.1:2012 -> 127.0.0.1:35774 [AP]
{"id":1,"result":null,"error":"SERVER_ERROR: [pos 85]: bytes or string in the stream must be decoded into a slice or array of bytes, not utils.RSRParsers"}

#
T 2018/08/02 11:42:16.797765 127.0.0.1:2012 -> 127.0.0.1:35751 [AP]
{"id":1,"result":null,"error":"ATTRIBUTES_ERROR:SERVER_ERROR: [pos 85]: bytes or string in the stream must be decoded into a slice or array of bytes, not utils.RSRParsers"}

```

Please, fix.

Thanks,
Michael

**Comment by TeoV** [comment] 2018-08-03 08:04
Hi Michael,
I can't reproduce this issue . 
Here is what I did trying to reproduce :

1) flush data db and verify if it's empty
```
teo@teo:~$ redis-cli -n 10
127.0.0.1:6379[10]> flushdb
OK
127.0.0.1:6379[10]> dbsize
(integer) 0
127.0.0.1:6379[10]> KEYS *
(empty list or set)
```

2)Start the engine with custom config 
`cgr-engine -config_dir=/usr/share/cgrates/conf/samples/tutmysql
`
3) send the command via telnet : 
```
teo@teo:~$ telnet localhost 2012
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"method":"AttributeSv1.ProcessEvent","params":[{"AttributeIDs":null,"ProcessRuns":null,"Tenant":"golant","ID":"dmt:082b841","Context":"*sessions","Time":"2018-08-02T11:42:16.797133833+03:00","Event":{"Account":"12345","AnswerTime":"2018-08-02 11:42:16 +0300 IDT","Category":"data","Destination":"42502","Direction":"*out","EventName":"DIAMETER_CCR","OriginHost":"GatewayService-4-13-1.PTggsn.telco.net","OriginID":"GatewayService-4-13-1.PTggsn.telco.net;1533199336;167816175","RequestType":"*prepaid","SetupTime":"2018-08-02 11:42:16 +0300 IDT","Subject":"*attributes","Tenant":"golant","ToR":"*data","Usage":"10485760","cgr_flags":"*accounts;*attributes"}}],"id":1}
{"id":1,"result":null,"error":"NOT_FOUND"}
```

For the moment we will close this issue and if you still get this error please reopen this 

Thanks,
TeoV

**Closed by TeoV** 2018-08-03 08:04 UTC

**Comment by muxalko** [comment] 2018-08-05 18:54
Teo,
That is strange, also trying the API for setting attribute profile fails with similar message: 
```

#
POST /jsonrpc HTTP/1.1.
.
{
  "id":"0",
  "method":"ApierV1.SetAttributeProfile",
  "params":[
    {
      "Tenant":"golant",
      "ID":"ATTR_972587832508_SESSIONAUTH",
      "Contexts":["*sessions"],
      "FilterIDs":["*string:Account:972587832508"],
      "Attributes":[
          {
            "FieldName":"Subject",
            "Initial": "*any",
            "Substitute":"roam",
            "Append":false
          }
  ..],
      "Blocker":false,
      "Weight":10
    }
  ]
}
#

HTTP/1.1 200 OK.
.
{"id":"0","result":null,"error":"json: cannot unmarshal string into Go struct field Attribute.Substitute of type utils.RSRParsers"}

```

**Comment by muxalko** [comment] 2018-08-05 19:24
Just noticed that the API has changed. I belive the issue was because of the old attributeProfile data being used with new version of cgrates (where Substitute field was changed from string to util.RSRParsers).

Trying the new Substitute format is crashing cgr-engine.
```
POST /jsonrpc HTTP/1.1.
{
  "id":"0",
  "method":"ApierV1.SetAttributeProfile",
  "params":[
    {
      "Tenant":"golant",
      "ID":"ATTR_972587832508_SESSIONAUTH",
      "Contexts":["*sessions"],
      "FilterIDs":["*string:Account:972587832508"],
      "Attributes":[
          {
            "FieldName":"Subject",
            "Initial": "*any",
            "Substitute": [
                {
                  "Rules":"roam",
                  "AllFiltersMatch": true
                }
          .],
            "Append":false
          }
  ..],
      "Blocker":false,
      "Weight":10
    }
  ]
}
```

Crash:
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7aa151]

goroutine 99 [running]:
github.com/cgrates/cgrates/utils.(*RSRParser).Compile(0xc4203b9800, 0xc420126d00, 0xc4204f77e0)
        /home/golan/proj/src/github.com/cgrates/cgrates/utils/rsrparser.go:192 +0x61
github.com/cgrates/cgrates/utils.RSRParsers.Compile(0xc42000f5c0, 0x1, 0x1, 0x1, 0x1)
        /home/golan/proj/src/github.com/cgrates/cgrates/utils/rsrparser.go:61 +0x4d
github.com/cgrates/cgrates/engine.(*AttributeProfile).compileSubstitutes(0xc4200a1170, 0xc420463d00, 0x1d)
        /home/golan/proj/src/github.com/cgrates/cgrates/engine/libattributes.go:60 +0x6b
github.com/cgrates/cgrates/engine.(*AttributeProfile).Compile(0xc4200a1170, 0xc420459dd8, 0x6)
        /home/golan/proj/src/github.com/cgrates/cgrates/engine/libattributes.go:70 +0x39
github.com/cgrates/cgrates/engine.(*DataManager).GetAttributeProfile(0xc4203c6f20, 0xc420459dd8, 0x6, 0xc420463d00, 0x1d, 0x1, 0x0, 0x0, 0x1c, 0x1c, ...)
        /home/golan/proj/src/github.com/cgrates/cgrates/engine/datamanager.go:1089 +0x281
github.com/cgrates/cgrates/engine.(*DataManager).SetAttributeProfile(0xc4203c6f20, 0xc4200a10e0, 0xc420593a01, 0x2, 0x2)
        /home/golan/proj/src/github.com/cgrates/cgrates/engine/datamanager.go:1098 +0xa7
github.com/cgrates/cgrates/apier/v1.(*ApierV1).SetAttributeProfile(0xc4204c1a00, 0xc4200a10e0, 0xc420459ef0, 0x0, 0x0)
        /home/golan/proj/src/github.com/cgrates/cgrates/apier/v1/attributes.go:47 +0xaf
reflect.Value.call(0xc420129aa0, 0xc42011fce8, 0x13, 0x1071219, 0x4, 0xc420593f20, 0x3, 0x3, 0x0, 0x0, ...)
        /home/golan/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc420129aa0, 0xc42011fce8, 0x13, 0xc42016ff20, 0x3, 0x3, 0x0, 0x0, 0x0)
        /home/golan/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420466ec0, 0xc420118200, 0xc420459c30, 0xc420534900, 0xc420463b80, 0xf4e2c0, 0xc4200a10e0, 0x16, 0xea7a00, 0xc420459ef0, ...)
        /home/golan/go/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
        /home/golan/go/src/net/rpc/server.go:481 +0x404
```

Could you please assist to figure out the correct format for Substitute ?
Should I open separate issue for that ?

Thanks,
Michael

**Comment by TeoV** [comment] 2018-08-06 07:24
Hi Michael,
In the first case, it's normal to give an error because as you said before the structure had changed.
In the second case I try to reproduce your issue but for me works.
Here is what I did :
1) Start fresh
```
teo@teo:~$ redis-cli -n 10
127.0.0.1:6379[10]> flushdb
OK
127.0.0.1:6379[10]> dbsize
(integer) 0
127.0.0.1:6379[10]> KEYS *
(empty list or set)
```

2) Start engine with tutmysql config.
`cgr-engine -config_dir=/usr/share/cgrates/conf/samples/tutmysql
`
3) Send the commands via telnet :

```
teo@teo:~$ telnet localhost 2012
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

#First set the attribute profile 

{
        "id": "0",
        "method": "ApierV1.SetAttributeProfile",
        "params": [{
                "Tenant": "golant",
                "ID": "ATTR_972587832508_SESSIONAUTH",
                "Contexts": ["*sessions"],
                "FilterIDs": ["*string:Account:972587832508"],
                "Attributes": [{
                        "FieldName": "Subject",
                        "Initial": "*any",
                        "Substitute": [{
                                "Rules": "roam",
                                "AllFiltersMatch": true
                        }],
                        "Append": false
                }],
                "Blocker": false,
                "Weight": 10
        }]
}
{"id":"0","result":"OK","error":null}

#Second verify the attribute profile if was set correct 

{
	"method": "ApierV1.GetAttributeProfile",
	"params": [{
		"Tenant": "golant",
		"ID": "ATTR_972587832508_SESSIONAUTH"
	}],
	"id": 24
}
{
	"id": 24,
	"result": {
		"Tenant": "golant",
		"ID": "ATTR_972587832508_SESSIONAUTH",
		"Contexts": ["*sessions"],
		"FilterIDs": ["*string:Account:972587832508"],
		"ActivationInterval": null,
		"Attributes": [{
			"FieldName": "Subject",
			"Initial": "*any",
			"Substitute": [{
				"Rules": "roam",
				"AllFiltersMatch": true
			}],
			"Append": false
		}],
		"Blocker": false,
		"Weight": 10
	},
	"error": null
}

#Simulate an event for this attribute

{
	"method": "AttributeSv1.ProcessEvent",
	"params": [{
		"APIKey": "",
		"AttributeIDs": null,
		"ProcessRuns": null,
		"Tenant": "golant",
		"ID": "",
		"Context": "*sessions",
		"Time": "2018-08-06T02:53:23.664961023-04:00",
		"Event": {
			"Account": "972587832508",
			"Subject": "test"
		}
	}],
	"id": 1
}
{
	"id": 1,
	"result": {
		"MatchedProfiles": ["ATTR_972587832508_SESSIONAUTH"],
		"AlteredFields": ["Subject"],
		"CGREvent": {
			"Tenant": "golant",
			"ID": "",
			"Context": "*sessions",
			"Time": "2018-08-06T02:53:23.664961023-04:00",
			"Event": {
				"Account": "972587832508",
				"Subject": "roam"
			}
		}
	},
	"error": null
}
```

Please make sure you are up to date with the current version 
```
teo@teo:~/go/src/github.com/cgrates/cgrates$ cgr-engine -version
CGRateS 0.9.1~rc8 git+0c1ed47 (2018-08-02T11:01:04-04:00)
```

Thanks,
TeoV

**Comment by muxalko** [comment] 2018-08-06 17:09
Hi Teo, 
Everything worked when I cleaned datadb, as per your example.
So, that was that chunk of mistype Substitute that caused the issue.
When is removed, it works fine.

Just out of curiosity, isn't that supposed to be handled when wrong type is sent over API ?
It is very easy to kill the service with wrong value type !!

For example, this query successfully kills cgr-engine, moreover, it is creating wrong type of key in datadb, which makes consequences (correct queries) to cause panic as well :
```
{
  "id":"0",
  "method":"ApierV1.SetAttributeProfile",
  "params":[
    {
        "Tenant": "golant",
        "ID": "ATTR_972587832508_SESSIONAUTH",
        "Contexts": [
            "*cdrs",
            "*sessions"
        ],
        "FilterIDs": [
            "*string:Account:972587832508"
        ],
        "ActivationInterval": {
            "ActivationTime": "2018-08-01T00:00:00Z",
            "ExpiryTime": "0001-01-01T00:00:00Z"
        },
        "Attributes": [
            {
                "FieldName": "Category",
                "Initial": "*any",
                "Substitute": [
                    {
                      "Id":"test"
                    }
                ],
                "Append": false
            }
        ],
        "Blocker": false,
        "Weight": 10
    }

  ]
}

```
