### ISSUE TITLE
[APIerSv1.AddBalance] Cdrlog crash

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#4192] opened 2023-11-13 11:04 UTC
Hi Teams,

```
go version go1.21.4 linux/amd64
* master df7ab8446 Ensure scheduler thread safety
```

If you set "Cdrlog" : "True" during call API.

```
cgr-engine[225615]: panic: runtime error: invalid memory address or nil pointer dereference
cgr-engine[225615]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x11b5249]
cgr-engine[225615]: goroutine 39655 [running]:
cgr-engine[225615]: github.com/cgrates/cgrates/engine.(*EventCost).FieldAsInterface(0x0, {0xc0023226d0, 0x1, 0x1})
cgr-engine[225615]: #011/usr/src/cgrates/engine/eventcost.go:955 +0x29
cgr-engine[225615]: github.com/cgrates/cgrates/engine.(*ExportRequest).FieldAsInterface(0xc0020e5470, {0xc0023226c0, 0x2, 0x2})
cgr-engine[225615]: #011/usr/src/cgrates/engine/exportrequest.go:69 +0x1d3
cgr-engine[225615]: github.com/cgrates/cgrates/engine.(*ExportRequest).FieldAsString(0xc000a09a71?, {0xc0023226c0?, 0x2e?, 0xc00101d9a0?})
cgr-engine[225615]: #011/usr/src/cgrates/engine/exportrequest.go:96 +0x18
cgr-engine[225615]: github.com/cgrates/cgrates/utils.DPDynamicString({0xc000a09a70?, 0x0?}, {0x2b959d0, 0xc0020e5470})
cgr-engine[225615]: #011/usr/src/cgrates/utils/dataprovider.go:72 +0xa7
cgr-engine[225615]: github.com/cgrates/cgrates/config.(*RSRParser).ParseDataProvider(0xc000903580, {0x2b959d0?, 0xc0020e5470?})
cgr-engine[225615]: #011/usr/src/cgrates/config/rsrparser.go:330 +0xf7
cgr-engine[225615]: github.com/cgrates/cgrates/config.RSRParsers.ParseDataProvider({0xc0000738e8, 0x1, 0x20?}, {0x2b959d0, 0xc0020e5470})
cgr-engine[225615]: #011/usr/src/cgrates/config/rsrparser.go:150 +0xae
cgr-engine[225615]: github.com/cgrates/cgrates/engine.ParseAttribute({0x2b959d0, 0xc0020e5470}, {0xc000a09a60?, 0xc00101dc50?}, {0xc000a09a40?, 0x1?}, {0xc0000738e8, 0x1, 0x1}, 0x8, ...)
cgr-engine[225615]: #011/usr/src/cgrates/engine/attributes.go:380 +0xae7
cgr-engine[225615]: github.com/cgrates/cgrates/engine.(*ExportRequest).ParseField(0xc0020e5470, 0xc000724120)
cgr-engine[225615]: #011/usr/src/cgrates/engine/exportrequest.go:196 +0x51f
cgr-engine[225615]: github.com/cgrates/cgrates/engine.(*ExportRequest).SetFields(0xc0020e5470, {0xc00098ee00, 0x1f, 0x4?})
cgr-engine[225615]: #011/usr/src/cgrates/engine/exportrequest.go:113 +0xeb
cgr-engine[225615]: github.com/cgrates/cgrates/ees.exportEventWithExporter({0x2ba2380, 0xc0023dd560}, 0xc000899a80, 0x16?, 0xc0002a4b40, 0xc000b8fe60)
cgr-engine[225615]: #011/usr/src/cgrates/ees/ees.go:287 +0xa4c
cgr-engine[225615]: github.com/cgrates/cgrates/ees.(*EventExporterS).V1ProcessEvent.func1(0x20?, 0x0, {0x2ba2380, 0xc0023dd560})
cgr-engine[225615]: #011/usr/src/cgrates/ees/ees.go:207 +0x79
cgr-engine[225615]: created by github.com/cgrates/cgrates/ees.(*EventExporterS).V1ProcessEvent in goroutine 39654
cgr-engine[225615]: #011/usr/src/cgrates/ees/ees.go:206 +0xbad
```

**Comment by gezimbll** [comment] 2023-11-15 15:03
Hi @Integration-IT ,

The issue is fixed on commit bf89dd765045bb236de86223aaf195d095715682 .

Thanks,
Gezim

**Closed by gezimbll** 2023-11-15 15:03 UTC
