### ISSUE TITLE
More descriptive FreeSWITCH return value in case of RALS error

### ISSUE THREAD

**Issue by nevian427** [cgrates/cgrates#941] opened 2018-02-05 16:28 UTC
Hi,
If Account not found or UNAUTHORIZED_DESTINATION
Feb  5 15:01:29 msk-vo-s-sbc3 journal: CGRateS <b089a61> [22424]: Account: example.ru:nevian, not found (NOT_FOUND)
Feb  5 15:01:29 msk-vo-s-sbc3 journal: CGRateS <b089a61> [22424]: <FreeSWITCHAgent> Could not authorize event r6wFNyOJI4, error: RALS_ERROR: ACCOUNT_NOT_FOUND

cgr_notify set to (SERVER_ERROR) expected something like ACCOUNT_NOT_FOUND or RALS_ERROR at least

Even more if we have
Feb  5 17:24:58 msk-vo-s-sbc3 journal: CGRateS <b089a61> [22424]: Rating plan not found for destination +978123456789 and account: example.ru:20, subject: *out:example.ru:nevian:random1
Feb  5 17:24:58 msk-vo-s-sbc3 journal: CGRateS <b089a61> [22424]: <Rater> Error getting cost for account key <example.ru:20>: RATING_PLAN_NOT_FOUND

cgr_notify set AUTH_OK!

Tried against 9ed38da86635d930d94bc44ee0b297a04b72bb1d in prepaid and postpaid mode

**Comment by nevian427** [comment] 2018-02-06 18:13
Looks like RATING_PLAN_NOT_FOUND not returned to FSAgent as err and auth always successful
but ACCOUNT_NOT_FOUND returned correctly
looks like UNAUTHORIZED_DESTINATION can be returned both ways (trying to find more info)

**Comment by nevian427** [comment] 2018-02-12 15:11
Trying to rephrase:
1. If we have no user we get cgr_notify as "SERVER_ERROR" while in syslog
 CGRateS <c84c468> [18454]: Account: example.ru:12997, not found (NOT_FOUND)
 CGRateS <c84c468> [18454]: <FreeSWITCHAgent> Could not authorize event ef4c5d00
-a791d64b-22f6a-3f40000a@10.0.64.63, error: RALS_ERROR: ACCOUNT_NOT_FOUND

2. If we have correct Account and Rating Plan but incorrect Destination we also get cgr_notify as "SERVER_ERROR" while in syslog
CGRateS <b089a61> [22424]: Destination +978123456789 not authorized for account
: example.ru:20, subject: *out:example.ru:call:20
CGRateS <b089a61> [22424]: <Rater> Error getting cost for account key <example.
ru:20>: UNAUTHORIZED_DESTINATION

3. If we have Account and NO correct Rating Plan found we have cgr_notify as "AUTH_OK" while in syslog
CGRateS <252e727> [20651]: Rating plan not found for destination +993123456789
and account: example.ru:20, subject: *out:euroset.ru:nevian:random1
CGRateS <252e727> [20651]: <Rater> Error getting cost for account key <example.
ru:20>: RATING_PLAN_NOT_FOUND

In cases 1 and 2 will be great to see RALS errors in cgr_notify.
Case 3 I believe we must not at least have AUTH_OK!

**Comment by danbogos** [comment] 2018-02-21 14:30
Hi @nevian427 

Can you please configure the connection between SessionS and rest of components over *json and attach here a capture? Also, please attach a capture for communication between FreeSWITCH and CGRateS.

Thanks,
DanB

**Comment by nevian427** [comment] 2018-02-21 16:30
[chan-park.txt](https://github.com/cgrates/cgrates/files/1744792/chan-park.txt)

Seems like these errors in syslog is after call end
Feb 21 19:22:59 msk-vo-s-sbc3 journal: CGRateS <a0ac1ef> [15540]: Rating plan not found for destination +993123456789 and account: euroset.ru:20, subject: *out:euroset.ru:test:random2
Feb 21 19:22:59 msk-vo-s-sbc3 journal: CGRateS <a0ac1ef> [15540]: <Rater> Error getting cost for account key <euroset.ru:20>: RATING_PLAN_NOT_FOUND

**Comment by danbogos** [comment] 2018-02-21 16:34
@nevian427 

We only auth *prepaid calls. For *postpaid calls, we don't check any errors since there is no need to authorize them.
The reason you see the errors is that you did not set up properly your rates/accounts and not because of wrong authorization from CGRateS side.

DanB

**Comment by nevian427** [comment] 2018-02-21 16:58
I had tried to set reqtype to *prepaid - calls authed OK. But hanguped immediately after ANSWER with INSUFFICIENT_CREDIT.
Goal is to stop call processing if we can't bill.

[chan-park2.txt](https://github.com/cgrates/cgrates/files/1744926/chan-park2.txt)

**Comment by nevian427** [comment] 2018-02-21 17:00
Even in *postpaid mode we can see errors but not all

**Comment by danbogos** [comment] 2018-02-21 17:02
@nevian427 

Let's focus on one issue at the time please.

In your prepaid requests I see the following:

 `{"method":"Responder.GetDerivedMaxSessionTime","params":[{"CGRID":"bda0473708820e1c22bf2d42f4c2753593926401","RunID":"","OrderID":0,"OriginHost":"83.143.192.143","Source":"SMG_","OriginID":"pdRtlzq8LW","ToR":"*voice","RequestType":"*prepaid","Tenant":"euroset.ru","Category":"test","Account":"20","Subject":"20","Destination":"+993123456789","SetupTime":"2018-02-21T19:33:27+03:00","AnswerTime":"0001-01-01T00:00:00Z","Usage":0,"ExtraFields":{"Channel-Read-Codec-Name":"","Channel-Write-Codec-Name":"","Direction":"*out","DisconnectCause":"","PDD":"0s","Supplier":"","answermsec":"","progress_mediamsec":"","progressmsec":"","remote_media_ip":"","sip_from_user_stripped":"nevian","sip_network_ip":"10.186.45.70","waitmsec":""},"ExtraInfo":"","Partial":false,"Rated":false,"CostSource":"","Cost":-1,"CostDetails":null}],"id":2}


T 2018/02/21 19:33:28.024355 127.0.0.1:2012 -> 127.0.0.1:56910 [AP]
{"id":2,"result":-1,"error":null}
`

Which shows that the account has unlimited funds. Did u set AllowNegative for your account? A prepaid account needs to have AllowNegative set on false.

DanB

**Comment by nevian427** [comment] 2018-02-22 16:42
@danbogos 

You are right this was a prepaid user with AllowNegative==true
I have created test user with AllowNegative==false and get expected result in both modes(prepaid/postpaid)

[chan-park3.txt](https://github.com/cgrates/cgrates/files/1748727/chan-park3.txt)

**Comment by danbogos** [comment] 2018-02-22 16:44
@nevian427 

Np, issue still stands, we should improve errors going into cgr_notify, so will not close the issue until all fixed.

Please update google groups thread so people there will know that there is no issue with auth in CGRateS.

Thanks,
DanB

**Comment by nevian427** [comment] 2018-02-22 17:27
IMHO issue still exist - why we get error for UNAUTHORIZED_DEST but not for RATING_PLAN_NOT_FOUND? In my understanding we shouldn't get AUTH_OK in case of any error regardless of account/req type.

**Comment by danbogos** [comment] 2018-02-22 17:29
@nevian427,

Is RATING_PLAN_NOT_FOUND happening during authorization or after the call completed?

DanB

**Comment by nevian427** [comment] 2018-02-22 18:14
@danbogos,In syslog I see this after complete.Can’t understand why we see subset of errors and not all. Are these processed by different parts of code with complete different logic?I’m off if this leads to massive time-consuming code changes.-- Wbr, Serge via mobile22.02.2018, 20:29, "Dan Christian Bogos" <notifications@github.com>:@nevian427,
Is RATING_PLAN_NOT_FOUND happening during authorization or after the call completed?
DanB

**Comment by danbogos** [comment] 2018-02-22 18:18
@nevian427 

This is what I have explained you before. This is not part of the authorization but part of CDR processing after you hang up the call. 
So again, we only authorize *pseudoprepaid and *prepaid calls, rest are always receiving cgr_notify="AUTH_OK". This is not a bug but how it should work in order to be able to have different billing modes.  

DanB

**Comment by nevian427** [comment] 2018-02-22 21:29
@danbogosFrom that I see (and posted logs) it not depends on request type but only AllowNegative.Is this expected behavior?-- Wbr, Serge via mobile22.02.2018, 21:19, "Dan Christian Bogos" <notifications@github.com>:@nevian427
This is what I have explained you before. This is not part of the authorization but part of CDR processing after you hang up the call.
So again, we only authorize *pseudoprepaid and *prepaid calls, rest are always receiving cgr_notify="AUTH_OK". This is not a bug but how it should work in order to be able to have different billing modes.
DanB

**Comment by danbogos** [comment] 2018-02-22 21:32
AllowNegative should always be false, unless you have a purpose for it.

DanB

Am 22.02.2018 10:29 nachm. schrieb "nevian427" <notifications@github.com>:

**Comment by danbogos** [comment] 2018-04-20 07:28
Should be fixed in master.

**Closed by danbogos** 2018-04-20 07:28 UTC
